In [3]:
import pandas as pd
from sqlalchemy import create_engine
import os

# 1. reading sample for 1200 rows 
df = pd.read_csv("paysim.csv", nrows=1200)

# 2. Database connection link 
# Format: mysql+pymysql://username:password@localhost:3306/dbname
db_url = "mysql+pymysql://root:Yonkoluffy$3B@localhost:3306/paysim"
engine = create_engine(db_url)

# 3. pushing to mysql table directly
df.to_sql(name="paysim_raw", con=engine, if_exists="replace", index=False)

print(" Done! 1,200 rows successfully pushed into MySQL!")

 Done! 1,200 rows successfully pushed into MySQL!

In [4]:
# 1. Pull sample data into a Pandas DataFrame using engine
df = pd.read_sql("SELECT * FROM paysim_raw", con=engine)

# 2. PANDAS SELECT & WHERE EQUIVALENT:
# Filter for TRANSFER transactions with amount > 10000
transfers_df = df[(df['type'] == 'TRANSFER') & (df['amount'] > 10000)][['type', 'amount', 'nameOrig', 'nameDest']]

print("--- Transfers > $10,000 ---")
display(transfers_df.head())

# 3. PANDAS GROUP BY EQUIVALENT:
summary_df = df.groupby('type').agg(
    total_transactions=('amount', 'count'),
    total_volume=('amount', 'sum')
).reset_index()

print("\n--- Summary Grouped by Type ---")
display(summary_df)

--- Transfers > $10,000 ---

        type     amount     nameOrig     nameDest
19  TRANSFER  215310.30  C1670993182  C1100439041
24  TRANSFER  311685.89  C1984094095   C932583850
58  TRANSFER   62610.80  C1976401987  C1937962514
78  TRANSFER   42712.39   C283039401  C1330106945
79  TRANSFER   77957.68   C207471778  C1761291320

--- Summary Grouped by Type ---

       type  total_transactions  total_volume
0   CASH_IN                 185   28805499.31
1  CASH_OUT                 250   40504683.06
2     DEBIT                  71     341286.72
3   PAYMENT                 561    3319180.25
4  TRANSFER                 133   63778450.57